import img from "../assets/03.png";
export const PRODUCT_CONST: IPropsProduct[] = [
  {
    id: 1,
    picUrl: img,
    className: "border-2 border-base-color/gray-200 bg-white",
    title: "$10.30",
    subtitle: "T-shirts with multiple colors, for men",
  },
  {
    id: 2,
    picUrl: img,
    className: "border-2 border-base-color/gray-200 bg-white",
    title: "$10.30",
    subtitle: "T-shirts with multiple colors, for men",
  },
  {
    id: 3,
    picUrl: img,
    className: "border-2 border-base-color/gray-200 bg-white",
    title: "$10.30",
    subtitle: "T-shirts with multiple colors, for men",
  },
  {
    id: 4,
    picUrl: img,
    className: "border-2 border-base-color/gray-200 bg-white",
    title: "$10.30",
    subtitle: "T-shirts with multiple colors, for men",
  },
  {
    id: 5,
    picUrl: img,
    className: "border-2 border-base-color/gray-200 bg-white",
    title: "$10.30",
    subtitle: "T-shirts with multiple colors, for men",
  },
  {
    id: 6,
    picUrl: img,
    className: "border-2 border-base-color/gray-200 bg-white",
    title: "$10.30",
    subtitle: "T-shirts with multiple colors, for men",
  },
  {
    id: 7,
    picUrl: img,
    className: "border-2 border-base-color/gray-200 bg-white",
    title: "$10.30",
    subtitle: "T-shirts with multiple colors, for men",
  },
  {
    id: 8,
    picUrl: img,
    className: "border-2 border-base-color/gray-200 bg-white",
    title: "$10.30",
    subtitle: "T-shirts with multiple colors, for men",
  },
  {
    id: 9,
    picUrl: img,
    className: "border-2 border-base-color/gray-200 bg-white",
    title: "$10.30",
    subtitle: "T-shirts with multiple colors, for men",
  },
  {
    id: 10,
    picUrl: img,
    className: "border-2 border-base-color/gray-200 bg-white",
    title: "$10.30",
    subtitle: "T-shirts with multiple colors, for men",
  },
];
