export const links = [
  {
    id: 1,
    label1: "About",
    label2: "About Us",
    label3: "Find store",
    label4: "Categories",
    label5: "Blogs",
    url: "/",
  },
  {
    id: 2,
    label1: "Partnership",
    label2: "About Us",
    label3: "Find store",
    label4: "Categories",
    label5: "Blogs",
    url: "/",
  },
  {
    id: 3,
    label1: "Information",
    label2: "About Us",
    label3: "Find store",
    label4: "Categories",
    label5: "Blogs",
    url: "/",
  },
  {
    id: 4,
    label1: "For users",
    label2: "About Us",
    label3: "Find store",
    label4: "Categories",
    label5: "Blogs",
    url: "/",
  },
  {
    id: 5,
    label1: "Get app",
    label2: "About Us",
    label3: "Find store",
    label4: "Categories",
    label5: "Blogs",
    url: "/",
  },
];
